function [S] = euler_source(x, coefs, px, py)

[rho, drhodx, drhody] = peval(x, coefs(:,1), px, py);
[u, dudx, dudy] = peval(x, coefs(:,2), px, py);
[v, dvdx, dvdy] = peval(x, coefs(:,3), px, py);
[p, dpdx, dpdy] = peval(x, coefs(:,4), px, py);
E = p/(rho*0.4) + 0.5*(u*u + v*v);
dedx = 1/(rho*0.4)*dpdx - p/(rho*rho*0.4)*drhodx...
     + u*dudx + v*dvdx;
dedy = 1/(rho*0.4)*dpdy - p/(rho*rho*0.4)*drhody...
     + u*dudy + v*dvdy;

S(1,1) = rho*(dudx + dvdy) + u*drhodx + v*drhody;
S(1,2) = dpdx + rho*u*(dudx + dvdy) ...
              + u*(u*drhodx + v*drhody)...
              + rho*( u*dudx + v*dudy);
S(1,3) = dpdx + rho*v*(dudx + dvdy) ...
              + v*(u*drhodx + v*drhody)...
              + rho*( u*dudx + v*dvdy);
S(1,4) = rho*e*( dudx + dvdy) ...
       + rho*( u*dedx + v*dedy ) ...
       + e*( u*drhodx + v*drhody ) ...
       + p*( dudx + dvdy ) ...
       + ( u*dpdx + v*dpdy );
